<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.0.4 (Python 3.6.5 on darwin)" generated="20190225 13:33:04.858">
<suite id="s1" name="Api Number Car" source="/Users/spartar/Documents/ProjectApplication/test1/cartacking/e2e/api_number_car.robot">
<test id="s1-t1" name="Get Requests">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>api</arg>
<arg>http://127.0.0.1:8000/number_car</arg>
</arguments>
<msg timestamp="20190225 13:33:04.967" level="INFO">Creating Session using : alias=api, url=http://127.0.0.1:8000/number_car, headers={},                     cookies=None, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20190225 13:33:04.967" endtime="20190225 13:33:04.968"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the</doc>
<arguments>
<arg>api</arg>
<arg>/</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20190225 13:33:04.987" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10da59ef0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /number_car/</msg>
<msg timestamp="20190225 13:33:05.189" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10da590f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /number_car/</msg>
<msg timestamp="20190225 13:33:05.593" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10dace2e8&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /number_car/</msg>
<msg timestamp="20190225 13:33:05.599" level="FAIL">ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /number_car/ (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10dace470&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</msg>
<status status="FAIL" starttime="20190225 13:33:04.968" endtime="20190225 13:33:05.599"></status>
</kw>
<status status="FAIL" starttime="20190225 13:33:04.966" endtime="20190225 13:33:05.599" critical="yes">ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /number_car/ (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10dace470&gt;: Failed to establish a new connection: [Errno 61] Connection refused',))</status>
</test>
<status status="FAIL" starttime="20190225 13:33:04.860" endtime="20190225 13:33:05.600"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Api Number Car">Api Number Car</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20190225 13:33:04.987" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10da59ef0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /number_car/</msg>
<msg timestamp="20190225 13:33:05.189" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10da590f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /number_car/</msg>
<msg timestamp="20190225 13:33:05.593" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10dace2e8&gt;: Failed to establish a new connection: [Errno 61] Connection refused',)': /number_car/</msg>
</errors>
</robot>
